[nuvindu.calendar_project]
clientId = "put-the-client-id-here"
clientSecret = "put-the-client-secret-here"
refreshToken = "put-the-refresh-token-here"
email = "email-address-of-the-user"

# These configurations are for the attendees of the event
gmailClientId = "put-the-attendee-client-id-here"
gmailClientSecret = "put-the-attendee-client-secret-here"
gmailRefreshToken = "put-the-attendee-refresh-token-here"
attendees = [] # Add the email addresses of the attendees here
